name = "food"
main = "src/index.js"
workers_dev = true
compatibility_date = "2025-07-25"

[observability]
enabled = true

[[kv_namespaces]]
id = "84621e3307514a09ad71fda98934de5d"
binding = "FOOD_WHEEL_STORAGE"
